### ISSUE TITLE
LINE 1: SET idle_in_transaction_session_timeout = 1d

### ISSUE THREAD

**Issue by gallowaystorm** [ansible-community/awx-operator-helm#32]
Getting constant error of:

`Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/dispatch/worker/task.py", line 103, in perform_work
    result = self.run_callable(body)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/dispatch/worker/task.py", line 78, in run_callable
    return _call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/scheduler/tasks.py", line 30, in dependency_manager
    run_manager(DependencyManager, "dependency")
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/scheduler/tasks.py", line 20, in run_manager
    manager().schedule()
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/scheduler/task_manager.py", line 142, in schedule
    with advisory_lock(f"{self.prefix}_lock", lock_session_timeout_milliseconds=lock_session_timeout_milliseconds, wait=False) as acquired:
  File "/usr/lib64/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/awx/main/utils/pglock.py", line 26, in advisory_lock
    cur.execute(f"SET idle_in_transaction_session_timeout = {idle_in_transaction_session_timeout}")
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/awx/venv/awx/lib64/python3.11/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: trailing junk after numeric literal at or near "1d"
LINE 1: SET idle_in_transaction_session_timeout = 1d`

This seems linked to this fix in the normal AWX src code:

https://github.com/ansible/awx/pull/15352/files

Can we please get this change implemented in the helm chart?  This causes a lot of features not to work.

**Comment by oraNod** [comment]
Thanks for reporting this, @gallowaystorm 

Looking at the date on the [commit from Hao](https://github.com/ansible/awx/pull/15352/commits/f1ac7968a1704b091a4bf1239815a4eda13b4f4e) I guess this isn't in the [latest release of AWX](https://github.com/ansible/awx/releases/tag/24.6.1). Given that the helm chat is basically a deployment wrapper around AWX, it suggests that we need another release of AWX for that fix to land. However [AWX releases are paused](https://forum.ansible.com/t/streamlining-awx-releases/6894#p-17699-pausing-releases-5) while refactoring and modernization work is taking place. You can find full details about that effort in the forum with the [awx-modernization tag](https://forum.ansible.com/tag/awx-modernization).

You might also find some solutions to workaround that issue in the forum. I did a quick search for that error you shared and found at least one post that seems relevant: https://forum.ansible.com/t/awx-jobs-stuck-pending-after-upgrade-to-2-19-1-v24-6-1/10191/5

I hope this is somewhat helpful. Cheers.

**Comment by gallowaystorm** [comment]
@oraNod  Thank you for this information.  I have reviewed those and there are no workarounds it seems.  Seems the new release is the only way to fix it.  When do you think the AWX releases will resume again?  I tried looking on the forums you sent but did not see an answer for that.

**Comment by oraNod** [comment]
> @oraNod Thank you for this information. I have reviewed those and there are no workarounds it seems. Seems the new release is the only way to fix it. When do you think the AWX releases will resume again? I tried looking on the forums you sent but did not see an answer for that.

@gallowaystorm You're welcome. Unfortunately I don't have any information about when the AWX releases will resume right now. I'm aware the modernization work is ongoing so my feeling is that it will be a bit longer until they start up again. Sorry I don't have anything more substantial for you right now as I realize it's probably frustrating to be stuck with an error. I will ask around though and try to find out if anyone has any advice or workarounds. Cheers.
